### ISSUE TITLE
Selecting fields is not working

### ISSUE THREAD

**Issue by petedrennan** [etianen/django-watson#87] opened 2015-01-07 22:38 UTC
I am trying to select fields for the search, and it just doesn't seem to work. Currently using Django 1.7. Search works fine, but can't refine it.

My apps.py:

    from django.apps import AppConfig
    import watson

    class LocationsConfig(AppConfig):
        name = 'locations'

        def ready(self):
            Location = self.get_model('Location')
            watson.register(Location, fields=('name_std', 'alt_name', 'name',))

views.py:

        if q:
            cities = []
            for i in watson.filter(Location.objects.filter(locationtype="city"), q):
                each_item = Location.objects.get(id=i.id)
                cities.append(each_item)

I get search results, but not limited to the fields selected.

In fact, I have refined to:

    class LocationsConfig(AppConfig):
        name = 'locations'

        def ready(self):
            Location = self.get_model('Location')
            watson.register(Location.objects.filter(name="Sydney"), fields=('name_std', 'alt_name', 'name',))

And am still getting results without the name Sydney, so besides registering the model, the code just isn't working at all.
Any thoughts?

Gone through the process of buildwatson, no change.

**Comment by etianen** [comment] 2015-01-10 16:20
In addition to indexing the given fields, the __unicode__ method of the model will be indexed. Could this be the cause?

**Comment by petedrennan** [comment] 2015-01-10 23:13
That could be it - assuming that overrides the filter(name="Sydney")

Any way I can exclude the __unicode__ method?

**Comment by petedrennan** [comment] 2015-01-12 03:18
Thinking about it - filtering to exclude certain items should override the fields, should it not?

**Comment by etianen** [comment] 2015-01-12 15:09
The excluded fields are subtracted from the fields that would otherwise be included. So, fields=(“foo”, “bar”), exclude=(“bar”,) would result in “foo” being indexed, but not bar. However, it makes very little sense to combine the two specifiers, so this rarely comes up.

You can avoid indexing the unicode method by creating a custom SearchAdapter.

https://github.com/etianen/django-watson/wiki/registering-models#tweaking-search-weighting

The default get_title implementation returns __unicode__, so create an alternative implementation for that.

**Comment by petedrennan** [comment] 2015-01-12 23:42
Great, thanks. For now I've just changed my unicode :)

**Comment by petedrennan** [comment] 2015-02-11 22:47
Realized I need to change my unicode back - I've tried the suggestion but can't get the new search adapter working - what should it look like if I just want to exclude unicode?

**Closed** 2015-02-12 01:21 UTC
